<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Acceuil</title>
	<link rel="stylesheet" href="https://bootswatch.com/cyborg/bootstrap.min.css">
	<link rel="stylesheet" href="<?=CLIENT_ROOT?>/ressources/CSS/style.css">
</head>
<body>
	<div class="container">
		<h1>Bienvenue sur mon blog</h1>
		<?=$content?>
	</div>
	<script   src="https://code.jquery.com/jquery-1.12.4.min.js"   integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="   crossorigin="anonymous"></script>
	<script src="<?=CLIENT_ROOT?>/ressources/javascript/app.js"></script>
</body>
</html>